import React from 'react'

function AppLoading() {
    return (
        <>
            <div className='flex flex-col items-center justify-center h-screen'>
                <div className="loadingio-spinner-gear-nq4q5u6dq7r">
                    <div className="ldio-x2uulkbinbj ">
                        <div>
                            <div />
                            <div />
                            <div />
                            <div />
                            <div />
                            <div />
                            <div />
                        </div>
                    </div>
                </div>
                <p className="text-center text-lg md:text-2xl text-gray-600">Hang on, Logging you in...</p>
                <style
                    type="text/css"
                    dangerouslySetInnerHTML={{
                        __html:
                            "\n@keyframes ldio-x2uulkbinbj {\n    0% { transform: rotate(0deg) }\n   50% { transform: rotate(18deg) }\n  100% { transform: rotate(36deg) }\n}\n.ldio-x2uulkbinbj > div {\n  transform-origin: 112.00000000000001px 112.00000000000001px;\n  animation: ldio-x2uulkbinbj 0.186219739292365s infinite linear;\n}\n.ldio-x2uulkbinbj > div div {\n    position: absolute;\n    width: 24.64px;\n    height: 170.24px;\n    background: #0073b1;\n    left: 112.00000000000001px;\n    top: 112.00000000000001px;\n    transform: translate(-50%,-50%);\n}\n.ldio-x2uulkbinbj > div div:nth-child(1) {\n    width: 134.4px;\n    height: 134.4px;\n    border-radius: 50%;\n}\n.ldio-x2uulkbinbj > div div:nth-child(7) {\n    width: 98.56px;\n    height: 98.56px;\n    background: #ffffff;\n    border-radius: 50%;\n}.ldio-x2uulkbinbj > div div:nth-child(3) {\n  transform: translate(-50%,-50%) rotate(36deg)\n}.ldio-x2uulkbinbj > div div:nth-child(4) {\n  transform: translate(-50%,-50%) rotate(72deg)\n}.ldio-x2uulkbinbj > div div:nth-child(5) {\n  transform: translate(-50%,-50%) rotate(108deg)\n}.ldio-x2uulkbinbj > div div:nth-child(6) {\n  transform: translate(-50%,-50%) rotate(144deg)\n}\n.loadingio-spinner-gear-nq4q5u6dq7r {\n  width: 224px;\n  height: 224px;\n  display: inline-block;\n  overflow: hidden;\n  background: #ffffff;\n}\n.ldio-x2uulkbinbj {\n  width: 100%;\n  height: 100%;\n  position: relative;\n  transform: translateZ(0) scale(1);\n  backface-visibility: hidden;\n  transform-origin: 0 0; /* see note above */\n}\n.ldio-x2uulkbinbj div { box-sizing: content-box; }\n/* [ldio] generated by https://loading.io */\n"
                    }}
                />
            </div>

        </>
    )
}

export default AppLoading